import RootLayout from '@/app/layout';
import Header from '@/app/components/home/Header';
import Footer from '@/app/components/home/Footer';
import MainQuestion from '@/app/components/question/MainQuestion';
import {Metadata} from 'next';

export const metadata: Metadata = {
    title: 'Free AI Article Writer | F.A.Q',
    description: 'Generated by create next app',
}

const Question = () => {
    return <RootLayout>
        <Header />
        <MainQuestion />
        <Footer />
    </RootLayout>
}

export default Question
