"use client";

import {Plus_Jakarta_Sans} from 'next/font/google';
import './style.css';
import {useEffect, useState} from 'react';
import {useRouter} from 'next/navigation';
import {getUser} from '../lib/authenticated';


const inter = Plus_Jakarta_Sans({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function DashboardLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    const [isSuccess, setIsSuccess] = useState<boolean>(false);
    const { push } = useRouter();

    useEffect(() => {
        (async () => {
            const { user, error } = await getUser();

            if (error) {
                push("/pages/auth/signin");
                return;
            }

            // if the error did not happen, if everything is alright
            setIsSuccess(true);
        })();
    }, [push]);

    if (!isSuccess) {
        return <p>Loading...</p>;
    }

    return (
        <html lang="en">
        <body className={`${inter.className}`}>
                    {children}
        </body>
        </html>
    )
}
